<a href="https://colab.research.google.com/github/lugsantistebanji/WCS-IA/blob/main/WCS_IA_Quetes_Numpy_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy : Introduction

NumPy allows you to manipulate data in the form of an array.

Complete the missions below using NumPy.

---

## Mission 1 :

Display the version of NumPy you are running (as each library, you can use np.__version__)



In [12]:
import numpy as np

print(f"The NumPy version is : {np.version.full_version}")

The NumPy version is : 1.26.4


---

## Mission 2 :

Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4

**Expected result:**

`array([0.8, 0.6, 0.4])`

In [15]:
import numpy as np

new_np_array = np.array([0.8, 0.6, 0.4])

print(type(new_np_array))
print(len(new_np_array))
print(new_np_array)

<class 'numpy.ndarray'>
3
[0.8 0.6 0.4]


---

## Mission 3 :

Create a function that uses the `np.random.random()` function to return an array with 10 random elements, all of which must be greater than 0.25 and less than 1.0

**Example of expected result:**

`array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])`

In [24]:
import numpy as np

np.random.random(10) * (0.75) + 0.25

array([0.87151084, 0.40199936, 0.56564499, 0.92521271, 0.83166445,
       0.94311172, 0.26268574, 0.4511305 , 0.73877839, 0.32180499])

---

## Mission 4 :

What does the `np.empty()` method do? Don't just copy the documentation, explain in your own words here:

**The empty method in NumPy** `creates an uninitialized array with indeterminate values. In other words, it allocates memory space to store an array with a specific data type.`

In [26]:
import numpy as np

empty_array = np.empty((3, 2))
print(empty_array)

[[4.97001418e-310 0.00000000e+000]
 [4.96905067e-310 6.52523503e-310]
 [7.34370885e+223 1.48776569e+195]]


---

## Mission 5 :

Create an array filled with only zeros. You can choose the length of this array.

In [28]:
import numpy as np

zeros_array = np.zeros((6, 5))

print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---

## Mission 6 :

Create an array filled with 10 random integers.

In [32]:
import numpy as np

int_array = np.random.randint(low=10, high=100, size=10)

print(len(int_array))
print(int_array)

10
[43 87 68 36 63 29 46 26 37 62]


---

## Mission 7 :

Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.

In [36]:
import numpy as np

a = np.arange(0, 8, 1)
print(a)
random_array = np.random.choice(a, 50)
print(random_array)

[0 1 2 3 4 5 6 7]
[0 2 1 4 1 5 7 4 0 3 2 7 5 2 2 1 2 0 1 3 4 7 3 4 7 0 4 5 7 1 2 4 6 6 4 3 6
 2 6 1 7 3 4 3 0 5 7 4 7 7]
