<a href="https://colab.research.google.com/github/lugsantistebanji/WCS-IA/blob/main/WCS_IA_Quetes_Numpy_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Execute the cell below before starting the 1st mission.

In [3]:
import numpy as np

array_1 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54, 35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

array_1

array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

---

# Mission 1

Using Numpy, how many axes `array_1` has ?




In [8]:
len(array_1.shape)

1

Still using Numpy, how many dimensions `array_1` has?

In [6]:
array_1.ndim

1

Display the first element of `array_1`

In [9]:
array_1[0]

10

---

# Mission 2

Modify, using a `numpy` method, the `array_1` object to be an object that has two axes, including 1 row and 32 columns.  
Save it under the variable `array_2`.

In [26]:
array_2 = array_1.reshape(1,32)
print(array_2)
print(array_2.ndim)

[[10 40 45  5 66 91 43 75 40 28 55 45 31 71 67 54 54 35 64 27 12 93 17 91
  50 57 74 61 86 20 36 35]]
2


Now, modify `array_1` into an object that has 32 rows and only 1 column.  
Save it under the variable `array_3`.

In [14]:
array_3 = array_1.reshape((32, 1))
array_3.ndim

2

Access the first element of `array_2`, then of `array_3`.  

**What do you notice?**

The `first element of array_2` is the same `array_1`, and the `first element of array_3` is an array with the first element of `array_1` : 10  

**Why ?**

The first element of un n-dimensional array is the first element in the axis 0, it's a n-1-dimensional array if n is upper than 0 else its un element with a primitive type.

In [27]:
array_2_first = array_2[0]
array_3_first = array_3[0]

print(f"First element to array_2 : {array_2_first}")
print(f"First element to array_3 : {array_3_first}")

First element to array_2 : [10 40 45  5 66 91 43 75 40 28 55 45 31 71 67 54 54 35 64 27 12 93 17 91
 50 57 74 61 86 20 36 35]
First element to array_3 : [10]


---

# Mission 3

Access the value that is at index 3 of array `array_2`.  
Do it with Numpy way, then with Python way.

In [37]:
#python way
array_2[0][3]

#numpy way
array_2[0, 3]

5

Access the value which is at index 3 of array `array_3` in Numpy.

In [38]:
array_3[3, 0]

5

---

# Mission 4

Reshape `array_1` to be a 4-row, 8-column array,
rather than a 32-element vector.  
Save your array under the variable `array_4`.

In [36]:
array_4 = array_1.reshape(4, 8)
array_4

array([[10, 40, 45,  5, 66, 91, 43, 75],
       [40, 28, 55, 45, 31, 71, 67, 54],
       [54, 35, 64, 27, 12, 93, 17, 91],
       [50, 57, 74, 61, 86, 20, 36, 35]])

Access for each row, the values ​​of the columns which have the index 1 to 2 included.

In [42]:
print(array_4[:, 1:3])

[[40 45]
 [28 55]
 [35 64]
 [57 74]]


Access for rows at position 1 and 2 inclusive, the values ​​of all columns.

In [43]:
print(array_4[1:3, :])

[[40 28 55 45 31 71 67 54]
 [54 35 64 27 12 93 17 91]]


Access for the rows which have the index 2 to 3 inclusive, to the values ​​of the columns which have the index 3 to 5 inclusive.

In [44]:
print(array_4[2:4, 3:6])

[[27 12 93]
 [61 86 20]]


Select the first column, as well as the columns whose index is a multiple of 2.

In [45]:
print(array_4[::2, :])

[[10 40 45  5 66 91 43 75]
 [54 35 64 27 12 93 17 91]]


Select columns whose index is odd.

In [46]:
print(array_4[1::2, :])

[[40 28 55 45 31 71 67 54]
 [50 57 74 61 86 20 36 35]]


---

# Mission 5

Reshape your `array_1` vector into a 3-dimensional array.
Your 3-dimensional array should have 2 matrices, each of which has 4 rows and 4 columns.
Save your array under the variable `array_5`.

In [52]:
array_5 = array_1.reshape(2, 4, 4)
print(array_5)
array_5.ndim

[[[10 40 45  5]
  [66 91 43 75]
  [40 28 55 45]
  [31 71 67 54]]

 [[54 35 64 27]
  [12 93 17 91]
  [50 57 74 61]
  [86 20 36 35]]]


3

Use the .shape attribute to observe the number of axes for `array_5`.

In [54]:
print(array_5.shape)
len(array_5.shape)

(2, 4, 4)


3

Select all values ​​from the first matrix.

In [58]:
matrix_1 = array_5[0]
matrix_1

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54]])

Access for both matrices,
to the values ​​corresponding to the rows at index 1 and to the columns that have positions 3 and 4.

In [62]:
rows_1_columns_2_3 = array_5[:,1,2:4]
print(rows_1_columns_2_3)

[[43 75]
 [17 91]]


Access row values ​​at positions 2 to 3,
columns at indexes 1 to 3 included for the second matrix only.

In [64]:
rows_1_2_columns_1_to_3 = array_5[1, 1:3, 1:4 ]
print(rows_1_2_columns_1_to_3)

[[93 17 91]
 [57 74 61]]



Reshape `array_5` so that we have 8 rows and 4 columns.

In [65]:
array_6 = array_5.reshape(8, 4)
array_6

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54],
       [54, 35, 64, 27],
       [12, 93, 17, 91],
       [50, 57, 74, 61],
       [86, 20, 36, 35]])